spring.application.name=webhook

spring.datasource.url=jdbc:mysql://localhost:3306/webhooktest
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Your Meta webhook verify token
meta.verify.token=mySecret123

spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8090


jwt.secret=ThisIsMyVerySecretKeyForMsgClubProject123456

jwt.expiration=86400000

